# Generated by Django 3.2.7 on 2021-09-27 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='about',
            field=models.TextField(default=datetime.datetime(2021, 9, 27, 14, 7, 58, 673846, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
