# Generated by Django 3.2.7 on 2021-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('slug', models.SlugField(max_length=155)),
                ('premiere', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.png', upload_to='images/')),
                ('cover', models.CharField(choices=[('HA', 'Hard'), ('SO', 'Soft')], max_length=10)),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'books',
                'ordering': ('-premiere',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=155)),
                ('slug', models.SlugField(max_length=155, unique=True)),
            ],
        ),
    ]
